import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import AboutTile from '../components/AboutTile'
import AdminLogin from '../components/AdminLogin'
import AppBar from '../components/AppBar'
import Banner from '../components/Banner'
import Contact from '../components/Contact'
import Footer from '../components/Footer'
import Rooms from '../components/Rooms'

const rooms = [
  {
    id: 1,
    numero: '2Xl',
    href: '#',
    feature: ["Max 2personnes", "Television", "internet", "clean"],
    imageSrc: '/2.jpg',
    imageAlt: 'Front of zip tote bag with white canvas, black canvas straps and handle, and black zipper pulls.',
    price: 140,
  },
  {
    id: 2,
    numero: '2Xl',
    href: '#',
    feature: ["Max 2personnes", "Television", "internet", "clean"],
    imageSrc: '/1.jpg',
    imageAlt: 'Front of zip tote bag with white canvas, black canvas straps and handle, and black zipper pulls.',
    price: 140,
  },
  {
    id: 3,
    numero: '2Xl',
    href: '#',
    feature: ["Max 2personnes", "Television", "internet", "clean"],
    imageSrc: '/3.jpg',
    imageAlt: 'Front of zip tote bag with white canvas, black canvas straps and handle, and black zipper pulls.',
    price: 140,
  },

  // More products...
]


export default function Home() {

  return (
    <div className="">

      <Head>
        <title>Ivatsiro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <Banner />
        <Rooms />
        <AboutTile />
        <Contact />

      </main>



    </div>
  )
}
